### ISSUE TITLE
Composer call is missing after git clone

### ISSUE THREAD

**Issue by MrPetovan** [jodumont/docker-image-friendica#3]
Since version 3.6, Friendica requires Composer to be called for any install or update done through git. We actually bundle a version of the Composer.phar binary in the `bin/` folder of the Friendica project.

I believe a `php bin/composer.phar install` is missing after this:
https://github.com/jodumont/docker-image-friendica/blob/68bd7282472f49dcbabfe10c8233f7265f295817/root/etc/cont-init.d/20-config#L21
This would most certainly solve https://github.com/friendica/friendica/issues/4769

**Comment by jodumont** [comment]
it's almost ready I still fighting with URL rewrite and NGINX

libCurl PHP module |   | (required)https://github.com/friendica/friendica/wiki/Nginx-Install-Guide
-- | -- | --
GD graphics PHP module |   | (required)
OpenSSL PHP module |   | (required)
PDO or MySQLi PHP module |   | (required)
mb_string PHP module |   | (required)
XML PHP module |   | (required)
iconv PHP module |   | (required)
POSIX PHP module |   | (required)
ImageMagick PHP extension is installed |   |  
ImageMagick supports GIF |   |  
.htconfig.php is writable |   |  
view/smarty3 is writable |   | (required)
Generate encryption keys |   | (required)
Command line PHP (/usr/bin/php) |   |  
PHP cli binary |   | (required)
PHP register_argc_argv |   | (required)
URL rewrite is working |   | (required)
URL rewrite in .htaccess is not working. Check your server configuration.

but for the git part it is done
thank again for your cheer
